version: "3"

services:
  server:
    build: server/
    command: python ./httpserver.py
    ports:
    - 7777:7777

  client:
    build: client/
    command: python ./httpclient.py
    network_mode: host
    depends_on:
      - server
