version: "3"

services:
  server:
    build: server/
    command: python ./async_server.py
    ports:
    - 7777:7777

  client:
    build: client/
    command: python ./async_client.py
    network_mode: host
    depends_on:
      - server